# from https://gitlab.gwdg.de/tobi_public/quarto_test/-/blob/main/.gitlab-ci.yml
image: python:3.10

variables:
  QUARTO_VERSION: 1.3.361
  BASENAME: {{cookiecutter.project_slug}}
  BRANCH_NAME: "main"

before_script:
  - python -V

pages:
  script:
    - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
    - dpkg -i quarto-${QUARTO_VERSION}-linux-amd64.deb
    - quarto add --no-prompt kapsner/authors-block
    - pip install jupyter
    - quarto check install
    - quarto check jupyter
    - pip install -r requirements.txt
    - make revealjs
  artifacts:
    paths:
      - public
  only:
    - main
